# Generated by Django 4.0.1 on 2022-01-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0003_remove_book_id_remove_user_id_alter_book_serial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
