# Generated by Django 4.0.1 on 2022-01-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('regNo', models.IntegerField()),
                ('year', models.IntegerField()),
                ('borrowDate', models.DateTimeField()),
                ('returnDate', models.DateField()),
                ('bookNo', models.IntegerField()),
            ],
        ),
    ]
