# Generated by Django 4.0.1 on 2022-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='returnStatus',
            field=models.BooleanField(default=False),
        ),
    ]
