# Generated by Django 4.0.1 on 2022-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0007_rename_no_of_borrowed_book_no_of_times_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='no_of_times_borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
