# Generated by Django 4.0.1 on 2022-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serial', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=50)),
                ('date_of_pub', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('no_of_times_borrowed', models.IntegerField(default=0)),
                ('bookStock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
