# Generated by Django 4.0.1 on 2022-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('date_of_pub', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('no_of_times_borrowed', models.IntegerField(default=0)),
                ('bookStock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
