# Generated by Django 4.0.1 on 2022-01-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='serial',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
