# Generated by Django 4.0.1 on 2022-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('regNo', models.IntegerField()),
                ('year', models.IntegerField()),
                ('borrowDate', models.DateTimeField(auto_now_add=True)),
                ('returnDate', models.DateTimeField()),
                ('bookNo', models.IntegerField()),
                ('returnStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
